DROP DATABASE IF EXISTS DVDOrama_DB;
GO
CREATE DATABASE DVDOrama_DB;
GO
USE DVDOrama_DB;
GO

CREATE TABLE Users(
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Username NVARCHAR(100) NOT NULL UNIQUE,
    PasswordHash NVARCHAR(255) NOT NULL
);
GO

CREATE TABLE MovieCollection (
    Id INT IDENTITY(1,1) PRIMARY KEY,
    Barcode NVARCHAR(50) NOT NULL,
    UserId INT NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT GETUTCDATE(),
    CONSTRAINT FK_MovieCollection_Users FOREIGN KEY (UserId)
        REFERENCES Users(Id)
        ON DELETE CASCADE
);
GO